version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build # or any build command specific to your project

artifacts:
  files:
    - '**/*'